name: local_storage_profile
description: Local storage of profile
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  snaq_api:
    path: ../snaq_api

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
