name: snaq_api
description: A Dart API Client for the SNAQ API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.7.0
